# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: shopware-secret
  namespace: shopware
type: Opaque
stringData:
  APP_SECRET: "K3Vfm8sYvV7ZRFnP5x9TqU0GcJb6hWdE"
  DATABASE_URL: "mysql://shopware:shopware@mysql:3306/shopware"
  REDIS_URL: "redis://redis:6379"
  LOCK_DSN: "redis://redis:6379/2"
